configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/thamserios%2Fagentregistry-efdd0ccccfe264e746361d08c052e0def490ba986e06bcbcbb617cfe196db82a.yml
openapi_spec_hash: 30ed92da57b2df98ef7304159d568bcf
config_hash: c96f1e231ed0db8caa6e7f8bbaf52787
